# Publish module to PowerShell Gallery
name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Create subdirectory for publish-powershell-module-action
          path: 'module'

      # Publish module
      - name: Publish PowerShell Module
        # You may pin to the exact commit or the version.
        uses: Akaizoku/publish-powershell-module-action@a1e0778a4a8ec283695a1d815461011e91c8319c
        with:
          # The NuGet API Key for PowerShell Gallery, with permission to push this module.
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
